### ISSUE TITLE
Не работает деплой на gitlab-pages

### ISSUE THREAD

**Issue by ibadin** [prikhodkin/gulp_prikhodkin#20]
Задача падает с ошибкой:

```
gulp build --production
SyntaxError: Invalid regular expression: /^.*?\((?<label>.*?)[,)]/: Invalid group
    at Object.<anonymous> (/builds/pxlpro/ramada/node_modules/ow/dist/source/index.js:1:26679)
    at r (/builds/pxlpro/ramada/node_modules/ow/dist/source/index.js:1:186)
    at Object.module.exports.r (/builds/pxlpro/ramada/node_modules/ow/dist/source/index.js:1:11962)
    at r (/builds/pxlpro/ramada/node_modules/ow/dist/source/index.js:1:186)
    at module.exports.Object.defineProperty.value (/builds/pxlpro/ramada/node_modules/ow/dist/source/index.js:1:985)
    at Object.<anonymous> (/builds/pxlpro/ramada/node_modules/ow/dist/source/index.js:1:994)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `gulp build --production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-07T09_11_12_259Z-debug.log
```

**Comment by prikhodkin** [comment]
Fixed
